### ISSUE TITLE
Search bar improvements

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#1460] opened 2020-12-05 11:42 UTC
One thing I found myself confused by recently is the functionality which allows you to jump to a project you already have. It looks like this currently:

![2020-12-05-123842_453x187_scrot](https://user-images.githubusercontent.com/40774/101241507-0134ed80-36f7-11eb-8681-9edc9b6db992.png)

I didn't realize I was already following upstream, so when I saw this, I thought "hmm it looks like the widget didn't load properly, where's the follow button?"

I think an improvement would be to include some information, when the project is available locally:

* Some kind of indicator that the project is already followed, eg. `[Following]` or `[local]`.
* Some kind of indicator that clicking on it or pressing enter will navigate to the project, like `-> [enter] to navigate` or just an arrow or something that says "go".

**Comment by xla** [comment] 2020-12-05 11:45
Looks like a duplicate of #1031 - maybe leave your thoughts in there.

**Closed** 2020-12-05 11:49 UTC
Labels: design
