### ISSUE TITLE
CPU leak while Radicle Upstream running in background

### ISSUE THREAD

**Issue by Zerim** [radicle-dev/radicle-upstream#2117] opened 2021-07-09 23:40 UTC
Intermittently, I'll find that the `radicle-proxy` process is eating upwards of 100% CPU and sometimes it reads near 1000% CPU in activity monitor. This is typically accompanied by my Macbook Pro feeling extremely hot and the fans running at full blast.

I have seen this on Radicle Upstream versions 0.2.4 and 0.2.6. I'm running MacOS Mojave 10.14.6. 

Typically I observe this while Radicle Upstream has been on in the background for some time, though I have also observed it not very long after restarting the Radicle Upsream client.

**Comment by geigerzaehler** [comment] 2021-07-12 09:08
Thanks for creating this issue @Zerim. You’re not the first one reporting this and we are looking into it. Could you tell us what seeds you are connected to? You can find this information on the settings screen. It would also be helpful if you could start Upstream from the command line and save the log output.

**Comment by geigerzaehler** [comment] 2021-07-15 15:18
There’s a chance that the new release [v0.2.8](https://radicle.community/t/radicle-upstream-v0-2-8-is-out/2434) has fixed it. Could you check @Zerim?

**Comment by Zerim** [comment] 2021-07-15 21:18
Thanks for following up! I'll definitely give 0.2.7.8 a try, but I won't have a chance until the week after next. So will get back to you then.

In the meantime, here is a video of some of the logs I'm seeing from Radicle while its CPU usage was around 600-800%. Logs were moving too fast to easily copy/paste so I just screen recorded.

https://user-images.githubusercontent.com/1834575/125858373-1a7e4c60-a515-47b3-beaf-277c4f85c79a.mov

**Comment by rudolfs** [comment] 2021-07-19 16:12
This seems to be a duplicate of https://github.com/radicle-dev/radicle-upstream/issues/1855. I just confirmed that this still happens on master at c3f140fa08607d2d136eeefdec1c435ab7fd530b.

Could we close this issue in favour of #1855?

**Closed** 2021-07-20 10:00 UTC
