### ISSUE TITLE
Decouple the feature flag from NODE_ENV

### ISSUE THREAD

**Issue by MeBrei** [radicle-dev/radicle-upstream#889] opened 2020-09-10 10:10 UTC
When starting the app with `yarn start` etc. it starts electron with `NODE_ENV=development`. The feature flag `isDev()` depends on this environment. 

To develop the app flexibly and see what features the production user will see, it should be possible to set the feature flag and environment easily and independently.

**Comment by xla** [comment] 2020-09-10 16:41
Duplicate of #888

**Closed by xla** 2020-09-10 16:41 UTC
Labels: improvement
