### ISSUE TITLE
Add another layer of tabs within Patches

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2834] opened 2022-05-12 12:51 UTC
This is in preparation to adding patch commenting.
For now we can only show the "Commits" tab.

- ~~move the `checkout`, `merge` and `close` buttons to the top tab bar and make them available only in the `patch` context~~ -> https://github.com/radicle-dev/radicle-upstream/commit/91683cb1b3c3a130955e5f505a8398de8c7d7e8d
- ~~move the `checkout project` button to the `files` context~~ -> https://github.com/radicle-dev/radicle-upstream/commit/91683cb1b3c3a130955e5f505a8398de8c7d7e8d
- ~~add a link icon that copies the shareable id to the clipboard~~ -> https://github.com/radicle-dev/radicle-upstream/commit/91683cb1b3c3a130955e5f505a8398de8c7d7e8d
- ~~remove the `main` <- `patchID` component~~ -> https://github.com/radicle-dev/radicle-upstream/commit/91683cb1b3c3a130955e5f505a8398de8c7d7e8d

Proposed:
<img width="1440" alt="Single Patch - Commits" src="https://user-images.githubusercontent.com/158411/168078498-9919a9df-f88a-4283-a871-9afb7c2937e4.png">

What we have now:
<img width="1840" alt="Screenshot 2022-05-12 at 16 50 36" src="https://user-images.githubusercontent.com/158411/168103784-c98eb79d-d2fb-40f1-8e7e-926c7325f0ba.png">

**Comment by Kaihuang724** [comment] 2022-05-16 14:47
@brandonhaslegs - Do you think it might be a good idea to add some color to the "Close Patch" and other actions in the top bar in the proposed design? It might be good for users to have positive/negative feedback at a quick glance.

**Comment by efstajas** [comment] 2022-05-16 15:12
![image](https://user-images.githubusercontent.com/1018218/168624788-60021983-f261-46b2-8934-5408d592d222.png)

Currently there's two different "Commits" tabs, one project-level, one patch-level, and at least at first glance it's visually a bit unclear which one is for which.

I feel like we should move the project-level tabs to the grey bar at the top, together with all the other project-level information. That could make hierarchy a lot clearer.

**Comment by brandonhaslegs** [comment] 2022-05-17 11:19
@Kaihuang724 I thought having two colored buttons up there felt really intense. This is what I tried though:

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/4406983/168799152-fadb777d-b147-430c-9695-a6a2a729bf58.png">

**Comment by brandonhaslegs** [comment] 2022-05-17 11:24
@efstajas Yep, we've always wanted to try to figure this out. IMO this design would look a bit less confusing if it was built how it was intended, with the "collapsed header" seen here:

<img width="825" alt="image" src="https://user-images.githubusercontent.com/4406983/168800062-e531d2df-2818-4baf-ad75-b57479467074.png">

**Comment by Kaihuang724** [comment] 2022-05-18 03:30
> @Kaihuang724 I thought having two colored buttons up there felt really intense. This is what I tried though:
> 
> <img alt="image" width="1318" src="https://user-images.githubusercontent.com/4406983/168799152-fadb777d-b147-430c-9695-a6a2a729bf58.png">

Yeah that is kinda intense. Another option could be a simple modal that gets triggered when a user is closing a patch, like "Are you sure you want to close this? It's irreversible"

**Comment by brandonhaslegs** [comment] 2022-05-18 05:52
Yes we should do the modal for sure!

**Comment by geigerzaehler** [comment] 2022-06-07 12:48
Can we close this @rudolfs?

**Closed** 2022-06-07 13:52 UTC
