### ISSUE TITLE
Running AppImage on Linux prints electorn warning

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1340] opened 2020-11-24 18:16 UTC
When starting the `0.1.0` binary it logs this electron warning:

```
(node:2894) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
```

Ref #1336

**Comment by geigerzaehler** [comment] 2020-11-25 09:39
Duplicate of #1307

**Closed by geigerzaehler** 2020-11-25 09:39 UTC
Labels: improvement, infrastructure
