### ISSUE TITLE
Double unseal crashes the proxy

### ISSUE THREAD

**Issue by tmakarios** [radicle-dev/radicle-upstream#2184] opened 2021-07-27 05:22 UTC
I ran Upstream (version 0.2.8, I think) for about 10 minutes, then quit it.  A few seconds later, I remembered something I wanted to check, so I restarted Upstream, and it crashed.  Attached are the logs of both runs.

[2021-07-22-radicle.txt](https://github.com/radicle-dev/radicle-upstream/files/6882867/2021-07-22-radicle.txt)
[2021-07-21-radicle-2.txt](https://github.com/radicle-dev/radicle-upstream/files/6882873/2021-07-21-radicle-2.txt)
[2021-07-21-radicle-2-errors.txt](https://github.com/radicle-dev/radicle-upstream/files/6882871/2021-07-21-radicle-2-errors.txt)

**Comment by geigerzaehler** [comment] 2021-07-28 14:04
Thanks for reporting this @tmakarios. It looks like there’s a race condition when the app tries to unlock the background process:

When you type in the password and ask the app to unlock we send `POST /v1/keystore/unseal` to the proxy to request and unlock. This request causes the proxy to reload. After the app receives a response it sends `GET /v1/session`. In your case, the proxy did not reload before the `GET /v1/session` request and that request told the app that the keystore is still sealed. The app then displayed the unlock screen a second time which resulted in a second `POST /v1/keystore/unseal` request which was sent after the proxy had finally reloaded.

It seems like the proxy is not able to handle an unseal request if it is already unsealed and this seems to be caused by the on-disk database not properly closing during the reload. This needs some more investigation.

To make this more robust the app should wait for the proxy to be unsealed after requesting the unseal. We can fix this by repeatedly requesting `GET /v1/session` until we don’t receive a 403 anymore.

**Comment by geigerzaehler** [comment] 2021-08-16 09:29
The PRs https://github.com/radicle-dev/radicle-upstream/pull/2237 and https://github.com/radicle-dev/radicle-upstream/pull/2163 should fix the issue. We’ll release a version with the fixes soon.

**Closed by geigerzaehler** 2021-08-16 09:29 UTC
