### ISSUE TITLE
Fix Device ID hover state bug on Profile

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2068] opened 2021-06-23 16:52 UTC
This one has been a bug forever! I hope it's easy because it happens to me all the time and it's so annoying!

The problem if you don't get it is that sometimes when moving the cursor over the Device ID really fast, it remains expanded instead of collapsing.

![device id hover expand bug](https://user-images.githubusercontent.com/4406983/123137222-06b81200-d454-11eb-91d8-70e5b0d76db9.gif)

**Comment by nishit-prasad** [comment] 2021-07-01 13:53
I can work on this after I finish with Issue #2073. Can it be assigned to me?

**Comment by brandonhaslegs** [comment] 2021-07-01 13:54
Sure thing, assigned!

**Comment by nishit-prasad** [comment] 2021-07-01 13:54
Thank you! I get to learn a lot. Appreciate it!

**Comment by juliendonck** [comment] 2021-07-01 14:40
> Thank you! I get to learn a lot. Appreciate it!

Happy to help where needed, feel free to message us on discord directly in the #upstream channel

**Comment by nishit-prasad** [comment] 2021-07-03 21:14
Follow-up/re-iteration regarding this issue: https://discord.com/channels/841318878125490186/843873418205331506/860745689657769984

Though it reproduces for me once in like 50 tries, it turns out that Svelte itself has this bug internally - `onmouseleave` event doesn't get fired sometimes.
I was able to reproduce this issue in their tutorial website: https://svelte.dev/tutorial/slot-props

It's not a bug in our code but in Svelte itself.
We can report this to them but since we don't know when that fix will roll out - do we change anything to get past this issue on our application specifically? Open to ideas.

**Comment by nishit-prasad** [comment] 2021-07-13 10:54
Further update. Did raise an issue on Svelte which they closed: https://github.com/sveltejs/svelte/issues/6520

In nutshell, they're mentioning that that when you run around pretty quick, especially during the time when `onmouseenter` and `onmouseleave` events overlap - we may see this issue since the browser is not able to recognize that.

So probably, I will change the hover logic such that they fire _only_ when necessary. I will keep posting more updates here.

**Comment by brandonhaslegs** [comment] 2021-07-14 10:27
Let's just make it not expand on hover. Then we have no issue anymore.

**Comment by nishit-prasad** [comment] 2021-07-16 05:01
PR is up and ready! 😄

**Closed** 2021-07-16 09:06 UTC
