### ISSUE TITLE
"Error: Incorrect input" when viewing remote

### ISSUE THREAD

**Issue by Zerim** [radicle-dev/radicle-upstream#2116] opened 2021-07-09 23:36 UTC
When trying to view a particular remote of a project in Radicle Upstream 0.2.6, I would get an error popup that allowed me to copy the following error message to my clipboard:

```{
  "stack": "Error: Incorrect input\n    at file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:2241346\n    at async Promise.all (index 0)\n    at async file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:2:2626499",
  "message": "Incorrect input",
  "code": "UnknownException",
  "details": {
    "name": "Error",
    "response": {}
  }
}
```

I'm on MacOS Mojave 10.14.6.

Unfortunately, I can no longer repro the error because I tried removing and re-adding the remote while troubleshooting and have not yet been able to successfully re-add the remote. I'm able to view another remote of the project totally fine.

**Comment by geigerzaehler** [comment] 2021-07-12 08:57
Thanks for reporting @Zerim. Unfortunately our error messages aren’t giving us any information here. (We’re addressing this in https://github.com/radicle-dev/radicle-upstream/pull/2118.) If you are able to reproduce this again you can gather more information by running the app from the terminal and saving the output.

If that is ok for you, I’d like to close this issue for now because there‘s very little for us to act on. Feel free to open this if it reoccurs and we have more information.

**Closed by geigerzaehler** 2021-07-12 08:57 UTC
