### ISSUE TITLE
Focus password field after filling in wrong password

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#1777] opened 2021-04-13 09:04 UTC
When filling in a wrong password, the user has to click on the field again to refocus the input. It should just stay focused and allow you to type again and press enter to retry.

**Comment by rudolfs** [comment] 2021-06-21 16:18
@juliendonck is this a duplicate of https://github.com/radicle-dev/radicle-upstream/issues/1179?

**Closed** 2021-06-22 07:56 UTC
