### ISSUE TITLE
non-ascii characters in path prevent branch selection in new project from existing repo

### ISSUE THREAD

**Issue by metasean** [radicle-dev/radicle-upstream#1590] opened 2021-02-06 21:17 UTC
_While this is clearly an edge case, it is also indicative that Unicode is not being used as a default, which is much less of an edge case_.

**Description of problem**
Having a non-ascii character (e.g. the Kanji glyph for "code" 典 i.e. [u+5178](http://www.unicode-symbol.com/u/5178.html)) in the file path, prevents selecting a branch other than `main`.

If the repo in question does _not_ have a `main` branch, _**then the project can't be created**_.
If the repo does have a `main` branch, then it will be the default branch (whether that's what the user wanted or not).

**Demo of problem**
Here a repo with only the branches `first`, `second`, and `third` can be choosen, but the drop-down for the "Default Branch" is disabled.
<img width="616" alt="existing_repo_choosen_default_branch_disabled" src="https://user-images.githubusercontent.com/7552754/107129662-2fb07f80-6884-11eb-9e51-9432e806b903.png">

Without a `main` branch, the project cannot be created.
<img width="1253" alt="error_message" src="https://user-images.githubusercontent.com/7552754/107129668-3b03ab00-6884-11eb-9b1d-606a16e53f83.png">

**Comment by rudolfs** [comment] 2021-09-29 07:04
Might have been solved by https://github.com/radicle-dev/radicle-upstream/pull/1807.

**Comment by geigerzaehler** [comment] 2021-09-29 07:53
Yes, this is a duplicate of #1806 and was fixed by #1807.

**Closed by geigerzaehler** 2021-09-29 07:53 UTC
Labels: bug
