### ISSUE TITLE
No tx logged when attesting identity

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2295] opened 2021-08-31 13:08 UTC
This was reported in the #support channel on discord. I could also reproduce this.

![txs](https://user-images.githubusercontent.com/158411/131508124-7ca0c79e-89e9-462c-ad5e-bf27bf75c575.png)

**Comment by geigerzaehler** [comment] 2021-08-31 13:16
Can you provide the steps how to reproduce this? Clicking on "link identity" works for me

**Comment by rudolfs** [comment] 2021-08-31 13:18
Hm, I just tested it again and it worked. I wonder if there's a race condition somewhere.

**Comment by rudolfs** [comment] 2021-08-31 13:53
I think this might happen if you refresh the app after you have confirmed the tx in the wallet and before the tx has been included. Perhaps when walletconnect is slow to respond?

**Comment by geigerzaehler** [comment] 2021-08-31 14:52
There’s a potential issue if the app reloads before we add the transaction to the local store but after it has been submitted to the network. In this may indeed be caused slow wallet connect. I don’t think there’s anything we can do about this.

**Comment by rudolfs** [comment] 2021-09-10 16:31
I just realised that we can reach this state also in the following way:

1. Onboard upstream
2. Create identity
3. Connect wallet
4. Attest identity on Ethereum, observe: there is an attestation transaction in the transaction list
5. In the Electron developer console <kbd>⌘</kbd>+<kbd>i</kbd> do `localStorage.clear()` and refresh the app <kbd>⌘</kbd>+<kbd>r</kbd>

Now the identity is attested but the transaction list is empty.

**Comment by Kaihuang724** [comment] 2022-03-19 21:27
Closing for now until we decide to implement blockchain features.

**Closed by Kaihuang724** 2022-03-19 21:27 UTC
Labels: bug
