### ISSUE TITLE
Multi user Radicle

### ISSUE THREAD

**Issue by bierlingm** [radicle-dev/radicle-upstream#2553] opened 2021-10-30 19:43 UTC
I would much appreciate the ability to create multiple Radicle identities and switching between them inside the Radicle Upstream app.

**Comment by rudolfs** [comment] 2021-11-01 08:28
This is already possible, albeit only from the CLI at the moment. Read more about profile switching in the [release notes](https://radicle.community/t/radicle-upstream-v0-2-3-is-out/2312). There's more info on the [`RAD_HOME` env](https://github.com/radicle-dev/radicle-upstream/blob/master/docs/development.md#running-multiple-upstream-instances-on-the-same-machine) variable in the docs too

I believe this issue is a duplicate of https://github.com/radicle-dev/radicle-upstream/issues/2261.

**Closed by rudolfs** 2021-11-01 08:28 UTC

**Comment by bierlingm** [comment] 2021-11-01 22:38
Thank you!!!
