### ISSUE TITLE
Managing remotes is not reflected in peer selector

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#1427] opened 2020-11-30 12:23 UTC
If you have the `alex` remote selected in a project, then "Manage Remotes" and "Unfollow" `alex`, you still see `alex` selected as remote, until you switch remotes.

**Comment by juliendonck** [comment] 2020-12-01 14:36
duplicate of #1210

**Closed by juliendonck** 2020-12-01 14:36 UTC
Labels: improvement, ui
