### ISSUE TITLE
Repo Creation Fails - macOS (10.15.7), Radicle Version (0.1.5)

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/radicle-upstream#1497] opened 2020-12-29 12:42 UTC
## Issue:

![image](https://user-images.githubusercontent.com/3743841/103284168-6916e500-49d2-11eb-8e5a-3da328195807.png)
Error:
```
{
  "code": "ProjectCreationFailure",
  "message": "Could not create project: the identity 'rad:git:hwd…5ic' already exists",
  "source": {
    "response": {}
  }
}
```

![image](https://user-images.githubusercontent.com/3743841/103284226-92d00c00-49d2-11eb-9d30-15038d95a36e.png)
Error:
```
{
  "code": "ProjectRequestFailure",
  "message": "The project bordumb_practice could not be loaded",
  "details": {
    "type": "defaultBranch",
    "urn": "rad:git:hwd1yren8bbh37iib8zq7ky1xgrh4t76ouixxewxoy7gj4b86ic5r9ot5ic",
    "shareableEntityIdentifier": "%rad:git:hwd1yren8bbh37iib8zq7ky1xgrh4t76ouixxewxoy7gj4b86ic5r9ot5ic",
    "metadata": {
      "name": "bordumb_practice",
      "description": "Practice repo",
      "defaultBranch": "main",
      "maintainers": [
        "rad:git:hwd1yredf4nhrtc7oguspzwoyeo1jzygkhahm5eubkqhqrruhpnkmzdenww"
      ]
    },
    "stats": null
  }
}
```

## My Best Guess
I tried using Radicle on a different computer (also on version 0.1.5). This failed altogether, so I tried on this new computer.
However, I ended up choosing the same exact username (bordumb) across both devices. 
So I wonder if that has anything to do with why it is saying `"Could not create project: the identity 'rad:git:hwd…5ic' already exists"`

If that is the cause of this issue, I think the initial sign-in/sign-up screen should be changed as it does not do anything to prevent such an issue (such as more seamlessly syncing a single account across multiple devices)

**Comment by FintanH** [comment] 2021-01-11 09:28
> However, I ended up choosing the same exact username (bordumb) across both devices.

That shouldn't matter in this case. What we're seeing here is that the _project_ already exists. But something that seems strange is that the project is also in a broken state -- it's missing its default branch.

Could you outline the steps that you took for creating the project if you still remember?

**Comment by bordumb** [comment] 2021-01-11 15:25
@FintanH Hey! Yes, the steps are pretty easy to replicate as it was the first time I ever used the desktop app

1. Download the desktop app
2. Open it
3. Click on "Start your first project" from the initial home page
4. Click on "Create a new repository"
5. Fill out all the steps 

Also, wacky thing is:
I just tried this on one of my computers with a new repo name and it ended up working fine
So it seems that the failed repository name that I tried reusing would throw an error (I guess for the reason you mentioned; it already existed but was corrupted).
So I think a good fix here might be to throw an error to the user (i.e. "This repository is corrupted, please use a different name") and possibly offer some way to uncorrupt it

**Comment by FintanH** [comment] 2021-01-11 15:33
Thanks for the extra detail @bordumb :) 

> So I think a good fix here might be to throw an error to the user (i.e. "This repository is corrupted, please use a different name") and possibly offer some way to uncorrupt it

<details>
<summary>:point_left: This is actually what we're attempting to do in the JSON you posted</summary>
```
{
  "code": "ProjectRequestFailure",
  "message": "The project bordumb_practice could not be loaded",
  "details": {
    "type": "defaultBranch",
    "urn": "rad:git:hwd1yren8bbh37iib8zq7ky1xgrh4t76ouixxewxoy7gj4b86ic5r9ot5ic",
    "shareableEntityIdentifier": "%rad:git:hwd1yren8bbh37iib8zq7ky1xgrh4t76ouixxewxoy7gj4b86ic5r9ot5ic",
    "metadata": {
      "name": "bordumb_practice",
      "description": "Practice repo",
      "defaultBranch": "main",
      "maintainers": [
        "rad:git:hwd1yredf4nhrtc7oguspzwoyeo1jzygkhahm5eubkqhqrruhpnkmzdenww"
      ]
    },
    "stats": null
  }
}
```
</details>

The issue is that a default branch wasn't created. That's a bit of a worry because we do our best to ensure that everything is validated before attempting to commit to any I/O actions. I guess something slipped through the cracks...

This particular case is documented here :point_right:  https://docs.radicle.xyz/docs/using-radicle/troubleshooting#defaultbranch

Do you think we're missing anything to improve the process of figuring out what went wrong?

**Comment by bordumb** [comment] 2021-01-11 15:59
@FintanH Those are some awesome docs!
I wasn't aware of those.

One idea might be:
Whenever there is an error, aside from the wonky JSON, maybe also include one line that (a) links the general trouble-shooting page (I wasn't aware of it before) and (b) another link to create an issue with you guys if they can't find a resolution

Also, if there is really good hygiene in terms of (a) the naming of errors + (b) the URLs used in the trouble-shooting guides, you might even find a way to cleanly link users to the exact trouble-shooting page for their issue

I'm cool if you close this issue by the way.
From my point of view, it's solved with my fix (creating a new repo name) and the docs

**Comment by FintanH** [comment] 2021-01-11 16:05
Thank you, I wanted to make sure I captured some feedback before closing :) Glad you have things working again!

**Closed by FintanH** 2021-01-11 16:05 UTC
Labels: bug, triage
