### ISSUE TITLE
Could not create project: the URN already exists

### ISSUE THREAD

**Issue by almereyda** [radicle-dev/radicle-upstream#2343] opened 2021-09-07 15:16 UTC
When reinitialising an existing git repository that was previously already registered with Radicle, but got lost after a version upgrade (0.2.9 > 0.2.10), adding it again is not possible, due to an error raised:

![Bildschirmfoto von 2021-09-07 17-15-07](https://user-images.githubusercontent.com/1645308/132369435-f8a54549-03c3-4bc8-924b-19e40f7c3912.png)

```
{
  "stack": "Error: Could not create project: the URN `rad:git:hnrkfugn7qwnse8k4r9e9dgdfk5p9sw3wijzy` already exists\n    at file:///tmp/.mount_radiclhHvE25/resources/app.asar/public/bundle.js:35:21729\n    at Generator.throw (<anonymous>)\n    at s (file:///tmp/.mount_radiclhHvE25/resources/app.asar/public/bundle.js:35:19761)",
  "message": "Could not create project: the URN `rad:git:hnrkfugn7qwnse8k4r9e9dgdfk5p9sw3wijzy` already exists",
  "code": "ProjectCreationFailure",
  "source": {
    "stack": "Error: the URN `rad:git:hnrkfugn7qwnse8k4r9e9dgdfk5p9sw3wijzy` already exists\n    at st.fetchOk (file:///tmp/.mount_radiclhHvE25/resources/app.asar/public/bundle.js:1:1622315)",
    "message": "the URN `rad:git:hnrkfugn7qwnse8k4r9e9dgdfk5p9sw3wijzy` already exists",
    "code": "UnknownException",
    "details": {
      "name": "Error",
      "variant": "IDENTITY_EXISTS",
      "body": {
        "message": "the URN `rad:git:hnrkfugn7qwnse8k4r9e9dgdfk5p9sw3wijzy` already exists",
        "variant": "IDENTITY_EXISTS"
      },
      "response": {}
    }
  }
}
```

**Comment by almereyda** [comment] 2021-09-07 15:18
This could have been broken in juggling around with #2342.

**Comment by rudolfs** [comment] 2021-09-07 15:28
So to understand this correctly: the project doesn't show up in the project list in your `Profile` -> `Projects` tab?

Does the repository that you're trying to add already have a `rad` remote?

**Comment by almereyda** [comment] 2021-09-07 16:40
Thank you for your questions.

Yes, the project which is also shared between the machines, already has the rad remote.

It will not show up in the list of projects, because it had not been added to this particular client/user/device, yet.

**Comment by rudolfs** [comment] 2021-09-07 16:45
Could you try to remove the rad remote with `git remote remove rad` and then try to create a project from it?

**Comment by almereyda** [comment] 2021-09-07 16:51
Yes, that worked flawlessly. Unfortunately it will be assigned a new Project ID, which is not the same as before on the other machine. Imagine the repository had been shared via sneakernet, and now one wants to collaborate via high latency networks with regular network splits (=offline), then this kind of portability of project directories is not given.

**Comment by rudolfs** [comment] 2021-09-07 20:23
> Unfortunately it will be assigned a new Project ID, which is not the same as before on the other machine. Imagine the repository had been shared via sneakernet, and now one wants to collaborate via high latency networks with regular network splits (=offline), then this kind of portability of project directories is not given.

Hm, that's an interesting use-case, I don't think it's possible at the moment. It might make sense to open another issue with this feature request.

**Comment by rudolfs** [comment] 2021-09-08 07:32
I'm going to close this one as it seem to be a duplicate of https://github.com/radicle-dev/radicle-upstream/issues/2343.

**Closed by rudolfs** 2021-09-08 07:32 UTC
