### ISSUE TITLE
Claim transaction sent by an invalid address

### ISSUE THREAD

**Issue by pimato** [radicle-dev/radicle-upstream#2158] opened 2021-07-21 08:01 UTC
Hey guys, I tried to connect an ethereum address with a radicle identity. The transaction got confirmed so should work but upstream tells me:

<img width="2461" alt="Bildschirmfoto 2021-07-21 um 09 59 50" src="https://user-images.githubusercontent.com/5337809/126453379-7ec09f49-b231-42be-8ff9-c237bd128015.png">

<img width="677" alt="Bildschirmfoto 2021-07-21 um 09 59 43" src="https://user-images.githubusercontent.com/5337809/126453361-b2646bf0-5b35-494a-aaae-a02e52ae9ce0.png">

```
{
  "stack": "Error: Claim transaction sent by an invalid address\n    at RC.getClaimedByTx (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:2382299)\n    at async gi.submit (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:1953062)",
  "message": "Claim transaction sent by an invalid address",
  "code": "UnhandledRejection",
  "details": {
    "name": "Error"
  }
}```

**Comment by CodeSandwich** [comment] 2021-07-21 08:46
Hi! Are you able to reproduce the error? What wallet are you using? Have you been switching network, wallet or account address while using Upstream?

**Comment by pimato** [comment] 2021-07-21 08:51
> Hi! Are you able to reproduce the error? 

Yes, I reconnected via wallet connect + gnosis safe and it still shows me this:
```
{
  "stack": "Error: Claim transaction sent by an invalid address\n    at RC.getClaimedByTx (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:2382299)\n    at async gi.submit (file:///Applications/Radicle%20Upstream.app/Contents/Resources/app.asar/public/bundle.js:1:1953062)",
  "message": "Claim transaction sent by an invalid address",
  "code": "UnhandledRejection",
  "details": {
    "name": "Error"
  }
}```
<img width="2082" alt="Bildschirmfoto 2021-07-21 um 10 50 08" src="https://user-images.githubusercontent.com/5337809/126460333-74de456a-771d-4956-99d3-3b9ebb973304.png">

> What wallet are you using?
Wallet Connect + Gnosis Safe

> Have you been switching network, wallet or account address while using Upstream?
No

**Comment by geigerzaehler** [comment] 2021-07-23 07:54
Hey @pimato. I’ve created a branch [`thomas/claim-errors`](https://github.com/radicle-dev/radicle-upstream/pull/2175) that adds more information to the error. Could you try running this and sending me the included data? You could already share your public address with me so I can investigate what may be wrong with the transaction. (The data is all public but feel free to share it privately via discord.)

**Comment by pimato** [comment] 2021-07-23 11:55
@geigerzaehler I do not get the error with your prepared version of upstream because I do not have the same radicle identity. After connecting via gnosis-safe through walletconnect the UI does not recognize the previous on-chain linking:
<img width="1455" alt="Bildschirmfoto 2021-07-23 um 13 55 08" src="https://user-images.githubusercontent.com/5337809/126778280-950a2b83-75eb-4eba-a5e5-00f3b9fdeead.png">

I will share with you my public address via Discord.

**Comment by geigerzaehler** [comment] 2021-07-23 16:23
Turns out that the error occurs because we’re assuming that the claims contract is called directly by a transaction. In your case, however, the claims contract is called by the gnosis safe and the claim is made for that safe. But the transaction that triggers this execution is initiated by a member of the safe. This means that the claimed address does not match the signer of the transaction.

Any idea how to address this @CodeSandwich? We can’t simply remove the check. In this case we can’t extract the claim payload from the transaction data directly. We probably need to get it from an internal call.

**Comment by CodeSandwich** [comment] 2021-07-26 09:57
Thank you both for investigating the issue!

I took a closer look at what's available when a transaction is internal and it turns out that it's basically nothing :grimacing: The notion of an "internal transaction" is a high-level concept and to obtain any information about it services like Etherscan need to run a modified version of EVM, which extracts the call history. From ethers.js' or web3.js' perspective the whole transaction is a black box, no data about internal transactions is available, all we get is a single calldata of the whole transaction and its logs. This makes the claims contract API infeasible for anything but direct EOA usage, because it requires access to `.claim` calldata for verification.

I'm afraid that the only universal solution is to modify the claims contract, so its events contain the payload. This forces us to trust the event content, which is much harder to verify than the calldata. We can't make event content unforgeable by signing it, because the smart contracts don't have private keys. We need to either trust the provider like Infura or use a verifiable alternative like The Graph. The only way to truly be sure that an even is legit would be to run a full Ethereum client, which is out of question for upstream users.

**Comment by geigerzaehler** [comment] 2021-07-26 10:34
As far as I know [events are also verifiable](https://ethereum.stackexchange.com/questions/16117/proving-the-existence-of-logs-to-the-blockchain#16120) through merkle proofs for the receipt root hash of a block

**Comment by CodeSandwich** [comment] 2021-07-26 10:45
Yeah, that's right, I've just found it too :D That's great news, because we can prove events regardless of their source.

So the solution seems simple: just add the payload to the event content. Unfortunately that requires deployment of a new contract and rejection of existing claims. I'll update the contract right now.

**Comment by CodeSandwich** [comment] 2021-07-26 11:11
That's doable, but I'm not sure if it's worth it. We have 25 valid (non-internal-call) claims on the mainnet, of which I suspect quite a few are our own or otherwise experimental. The logic to support both contracts will introduce some complexity and will forever generate more client requests.

**Comment by geigerzaehler** [comment] 2021-07-27 09:39
Makes sense to only support one contract but we would need to clearly communicate that to users that have existing attestations. @cloudhead do you want to weigh in on this?

**Comment by cloudhead** [comment] 2021-07-27 21:42
I don't have a good grasp of who these users might be, but I agree it's a burden you will have to carry forever and thus probably not worth it. However it's also shitty to just discard claims for legit users. If you can somehow figure out who these users are, then you could reach out to them. Otherwise, one suggestion would be to -- in the next release -- have a warning show up if you have a "legacy" claim, and ask the user to create a new claim. Eventually you can remove the warning and the support for legacy claims. How you approach this is in the end your decision though, upstream is the only app that uses these claims so far.

**Comment by geigerzaehler** [comment] 2021-07-28 13:28
Thanks for the input @cloudhead. This aligns with I discussed with @juliendonck too. So let’s find a way to inform the users that have already created claims that we’ll update the claims contract.

**Comment by geigerzaehler** [comment] 2021-07-28 13:34
I’ve summarized the work to be done in https://github.com/radicle-dev/radicle-upstream/issues/2188.

**Comment by rudolfs** [comment] 2022-02-18 20:45
Closing this in favour of #2188.

**Closed by rudolfs** 2022-02-18 20:45 UTC
