### ISSUE TITLE
Show an informative error when proxy is already running

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-upstream#1454] opened 2020-12-03 16:44 UTC
There are many cases where when starting up the app there is an existing proxy process which prevents the app to start up a new one. We have a descriptive error surfaced for it, which we can use to translate into a friendly error screen and potetially link to the FAQs.

/cc @abbey-titcomb

**Comment by rudolfs** [comment] 2022-02-18 18:04
Duplicate of https://github.com/radicle-dev/radicle-upstream/issues/1442.

**Closed by rudolfs** 2022-02-18 18:04 UTC
