### ISSUE TITLE
[working copy] Ensure checkout comes from selected peer

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-upstream#849] opened 2020-09-01 10:30 UTC
We have the checkout functionality, however, we have mostly tested on local projects. We want to confirm (or fix) that it works by checking out the peer that I select. For example, if I have `rudolfs@hsgfj` as a peer and I select his view of the project, then when I click checkout his default branch is selected for creating the working copy.

**Comment by rudolfs** [comment] 2020-09-14 12:24
Write a unit test that:
1. Sets up two peers
2. Clones project from one peer to the other
3. Does a working copy checkout on peer that cloned
Expected behaviour: the working copy is based off of `refs/namespaces/<project>/refs/remotes/<peer1>/heads/<default>`

**Comment by xla** [comment] 2020-09-14 12:38
Since #881 landed we have integrations tests in the coco crate. The replication suite might be a good place to assert this behaviour:

https://github.com/radicle-dev/radicle-upstream/blob/7851e9e651b2c8366a93fe2be3985622ca04d62e/proxy/coco/tests/replication.rs#L1-L217

**Comment by FintanH** [comment] 2020-09-24 14:31
Trying this out we run into a few _peculiarties_...

The first of which there's a failing test for here: https://github.com/radicle-dev/radicle-link/pull/336. Basically, a 3rd peer will not see the original maintainers `heads/*`. This is expected to be an issue since what branch would checkout from?!

The second is that in our test [here](https://github.com/radicle-dev/radicle-upstream/blob/fintan/checkout-peer/proxy/coco/tests/replication.rs#L328-L455), Bob cannot create the checkout of Alice's project.

The third is: getting the `PeerId` correct for the checkout is very important when testing locally because we could accidentally talk to another peer's storage when we meant to use "our own" `PeerId`.

Fourth: We're currently not sure how to tell the clone to base itself off of `refs/namespaces/<project>/refs/remotes/<peer1>/heads/<default>`.

**Closed** 2020-10-15 16:34 UTC
Labels: proxy
