### ISSUE TITLE
Fix project clone URL

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-upstream#557] opened 2020-06-23 14:35 UTC
Clone URL currently shows `rad:` prefix twice, eg. `rad:rad:git:hwd1yreyqjxk4ckaw9feq3obh4jntjd847868tj93984unsfa6adnagaqwy`

**Comment by rudolfs** [comment] 2020-07-02 15:03
Duplicate of: https://github.com/radicle-dev/radicle-upstream/issues/491.

**Closed by rudolfs** 2020-07-02 15:03 UTC
Labels: bug, easy, ui
