### ISSUE TITLE
App locks up due to wallet storage

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2023] opened 2021-06-18 08:14 UTC
I've seen this while developing. Not quite sure what the cause is, but it seems like there's a schema mismatch in the local storage.

To work around it, I do `localStorage.clear()` immediately followed by a hard refresh <kbd>shift</kbd>+<kbd>⌘</kbd>+<kbd>r</kbd>.

<img width="791" alt="Screenshot 2021-06-18 at 10 10 45" src="https://user-images.githubusercontent.com/158411/122529614-f6500380-d01d-11eb-8390-8fd3d952986e.png">

**Comment by geigerzaehler** [comment] 2021-06-18 08:54
This is caused by switching between two versions of the app. One that includes `Rinkeby` in `ethereuem.Environment` and stores it in local storage and an old version that does not know how to handle `Rinkeby`. This shouldn’t cause an issue for users so I’ll close this. But it might be a good idea to schema validate everything that we store in local storage.

**Closed by geigerzaehler** 2021-06-18 08:54 UTC
