### ISSUE TITLE
Switching network in settings displays orgs from other network

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle-upstream#2435] opened 2021-09-29 13:51 UTC
Steps to reproduce
1. Connected wallet is on mainnet, app settings is on rinkeby -> I don't see any orgs in sidebar
2. wallet page in app says to switch to mainnet
3. go to settings and switch from rinkeby to mainnet -> see the rinkeby orgs
4. refresh app -> see mainnet orgs

Video to show bug:
https://user-images.githubusercontent.com/2326909/135282027-27caf1ee-e58b-4117-babc-e9ae70fc350f.mp4

**Comment by rudolfs** [comment] 2021-09-29 14:09
Duplicate of https://github.com/radicle-dev/radicle-upstream/issues/2362.

**Closed by rudolfs** 2021-09-29 14:09 UTC
Labels: bug, ethereum
