### ISSUE TITLE
Make transaction terms consistent

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#572] opened 2020-06-24 11:40 UTC
A pending transaction has the wrong status text.

![image](https://user-images.githubusercontent.com/4406983/85547934-b2027100-b61e-11ea-9ee0-9dd8e3a8d436.png)

**Comment by juliendonck** [comment] 2020-06-24 12:30
related to #418

**Comment by xla** [comment] 2020-06-24 12:39
This is actually the correct state, as it is confirmed in a couple of blocks. Pending we refer to when the transaction has not been applied to any blocks. Understandably that is confusing especially with the obvious miss-match in this screen. We need to settle (no pun intended) on what lingo we want to present to users. From a purely technical domain understanding, a transcation goes from: Pending -> Confirmed -> Settled. Where the last stage is the one we communicate as complete/green.

@cloudhead Prob has some input on this.

**Comment by cloudhead** [comment] 2020-06-24 12:46
Wait so which one is correct? They can't both be, :man_shrugging: 

If I understand, the problem is that if we want to show a "global" progress, it's a little bit more tricky: what do you say if one transaction is confirmed, and one is still pending?

One solution would be to use a different set of states/language for the global view. Eg:

* Individual tx states: pending -> confirmed -> settled
* Global state: in progress -> complete

As long as there's one transaction that isn't settled, the global state would show "in progress".

**Comment by juliendonck** [comment] 2020-06-25 11:46
@cloudhead we already did the thinking around this here:
<img width="525" alt="Screenshot 2020-06-25 at 13 46 03" src="https://user-images.githubusercontent.com/2326909/85713983-4259b800-b6ea-11ea-825e-f23b656396e1.png">

Does this not make sense?

**Comment by cloudhead** [comment] 2020-06-25 11:49
It does, but doesn't say what the copy should be

**Comment by brandonhaslegs** [comment] 2020-07-01 12:21
We met and agreed to do the following:
- [ ] Change all "confirmed" states to "pending" in the transaction center
- [ ] Change the word "settled" to "completed" everywhere
- [ ] Calculate the progress circle based on pending states only (not completed or failed states)
- [ ] Summary text should say pending as long as there is at least one pending
- [ ] Show the more detailed pending status on the transaction modal (Pending confirmation, Pending completion)
- [ ]  Add "completed" status to all completed transaction modals

**Comment by juliendonck** [comment] 2020-08-03 12:27
Been trying to do this one, but changing the strings in the `StateType` enum causes a crash. I think my typescript knowledge is not good enough...

**Comment by xla** [comment] 2020-08-03 12:57
@juliendonck Can you open a draft PR with the crashing code? Can assist on moving this forward.

**Comment by xla** [comment] 2020-09-01 15:55
Regisry functionality has been remvoed.

**Closed by xla** 2020-09-01 15:55 UTC
Labels: improvement, ui
