### ISSUE TITLE
App does not handle system sleeping well

### ISSUE THREAD

**Issue by viraptor** [radicle-dev/radicle-upstream#1627] opened 2021-02-22 00:16 UTC
If I put my laptop to sleep while radicle-upstream is running (last tested on 0.1.10), the app doesn't recover the connections after wakeup.

The output contains repeated:
```
 INFO  librad::net::protocol > establishing connection remote.id=hyy4ebh8amk3ypyawgpjnfpbgkxqwdo5n1iif5s17yghwmewrf4d8a remote.addr=35.197.169.21:12345 
 WARN  librad::net::protocol > could not connect to hyy4ebh8amk3ypyawgpjnfpbgkxqwdo5n1iif5s17yghwmewrf4d8a at 35.197.169.21:12345: endpoint stopping 
 WARN  librad::net::gossip   > Failed to send shuffle to hybri79rzhi33474kxaatjesp4qhz4k7srsrx774jem5buqch6p7mk: Io(Custom { kind: Other, error: LocallyClosed }) 
 INFO  librad::net::protocol > establishing connection remote.id=hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw remote.addr=34.91.29.42:12345 
 WARN  librad::net::protocol > could not connect to hynewpywqj6x4mxgj7sojhue3erucyexiyhobxx4du9w66hxhbfqbw at 34.91.29.42:12345: endpoint stopping
```

**Comment by mkroehnert** [comment] 2021-02-25 21:27
seems to be duplicate of #1282

**Comment by xla** [comment] 2021-02-26 11:40
Closing in favour of #1282

**Closed by xla** 2021-02-26 11:40 UTC
