### ISSUE TITLE
Peer does not support any known protocol error

### ISSUE THREAD

**Issue by xni** [radicle-dev/radicle-upstream#1624] opened 2021-02-21 02:07 UTC
Hi! I'm trying to connect from Upstream 0.1.10 (Ubuntu) to my server: 95.216.68.43
And I can see such an error in the console.

```
Peer does not support any known protocol error
```

net stat shows that it is listening:

udp        0      0 0.0.0.0:12345           0.0.0.0:*                           2371/target/release

Nothing strange in the status messages on the server.

radicle-bins: f8338de0cfd6182eaa6d5c6392d545d515bb3dfe

What else can I provide to help you to investigate?

**Comment by geigerzaehler** [comment] 2021-02-22 08:55
Hey @xni. Did you forget to paste the error into your issue? Some detailed error messages should help us figure out what is going on.

**Comment by xni** [comment] 2021-02-22 09:43
Oh, sorry, the error message was in the subject, but I've copied it to the body as well :)

```
Peer does not support any known protocol error
```

I found a tip to checkout v. f1462b92a06ef65ec4b65201e9801473a41b4ee3 and it helped. Is it the expected behaviour (like we are updating proto, but upstream-client is not ready yet)

**Comment by geigerzaehler** [comment] 2021-02-22 09:50
Maybe @FintanH or @xla can shed some light on this but I believe that this is caused by an incompatible protocol upgrade that we’re working on. The latest official Upstream release works with the old version and I believe that your seed not version already uses the new version. This is we an old revision works for you.

**Comment by FintanH** [comment] 2021-02-22 09:53
Ya, the latest `master` in `radicle-bins` is not compatible. I've made a PR to bins to outline this https://github.com/radicle-dev/radicle-bins/pull/72/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

The latest will be compatible with Upstream once https://github.com/radicle-dev/radicle-upstream/pull/1463 lands.

**Comment by FintanH** [comment] 2021-02-22 09:54
I'm going to close this as there's nothing to remedy and hopefully it'll serve as having an answer for people running into the same issue. Thanks for opening and investigating @xni :blush:

**Closed by FintanH** 2021-02-22 09:54 UTC

**Comment by xni** [comment] 2021-02-22 10:12
Thanks for checking this, @FintanH !
