### ISSUE TITLE
Ethereum network in Upstream should be set to the wallet's network

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-upstream#2002] opened 2021-06-16 09:10 UTC
At the moment we disable certain features if the Ethereum network in Upstream is set to something different than what the user has selected in their connected wallet.

<img width="999" alt="Screenshot 2021-06-16 at 11 08 47" src="https://user-images.githubusercontent.com/158411/122191666-3a62cd00-ce93-11eb-9fba-ae081b7f4379.png">

Instead Upstream's Ethereum network setting should just follow whatever is set in the user's wallet to prevent having a mismatch in the first place.

**Comment by geigerzaehler** [comment] 2021-06-16 09:51
To implement this change we would need to remove `selectedEnvironment` from `ui/src/ethereum` and use `WalletConnect#chainId` instead. `selectedEnvironment` is only used by `ui/src/wallet`. It reacts to changes and re-builds the wallet based on the environment. The environment is used to instantiate an ethers provider and obtain addresses for all the contracts we interact with.

The main challenge of using `WalletConnect#chainId` instead of the selected environment is that at the moment the environment is used before WalletConnect is instantiated and before we know the chain ID. To address this it might be necessary move the contract address resolution into the contract facade objects and do it dynamically on every call. Similarly, for we would need to change `WalletConnectSigner` so that we can dynamically set the provider instead of passing it on construction.

Finally, we need to keep an option to use a local Ethereum node for development with ganache. A command line flag or environment variable should be enough for that.

I estimate that it takes three days to do this.

**Comment by geigerzaehler** [comment] 2021-09-01 14:09
After investigating this further I came to the conclusion that it’s not a good idea to have the connected wallet control the network while the app is running. This setup opens the door to a lot of issues caused by switching the network while some request is in progress.

I suggest we keep control of the network within the app. We can however make some improvements to the UX. We could move the network selection to the wallet screen. We could also use the network from the wallet when it is initially connected. To change the network, the user would need to reconnect to the wallet again.

**Comment by rudolfs** [comment] 2021-09-14 07:28
> After investigating this further I came to the conclusion that it’s not a good idea to have the connected wallet control the network while the app is running. This setup opens the door to a lot of issues caused by switching the network while some request is in progress.


The `ethers` docs mention reloading the UI on a network change as best practice. Maybe we could do that?

> So, the best practice when a network change occurs is to simply refresh the page. This should cause all your UI components to reset to a known-safe state, including any banners and warnings to your users if they are on an unsupported network.

https://docs.ethers.io/v5/single-page/#/v5/concepts/best-practices/-%23-best-practices--network-changes

**Comment by geigerzaehler** [comment] 2021-09-20 12:33
> The `ethers` docs mention reloading the UI on a network change as best practice. Maybe we could do that?

Good idea. We shouldn’t do it automatically though since it is quite intrusive. Maybe show a notification to the user that the network has been updated and provide a button that reloads the app.

**Comment by rudolfs** [comment] 2021-09-20 12:44
> Good idea. We shouldn’t do it automatically though since it is quite intrusive. Maybe show a notification to the user that the network has been updated and provide a button that reloads the app.

Yeah, that's what I was thinking.

**Comment by Kaihuang724** [comment] 2022-03-19 21:29
Closing for now until we decide to implement blockchain features.

**Closed by Kaihuang724** 2022-03-19 21:29 UTC
