### ISSUE TITLE
Inform user that they need modify their search path to use CLI tools

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-upstream#2760] opened 2022-02-10 14:21 UTC
To interact with Upstream on the command line the `git-remote-rad` helper needs to be in the search path. The same is true for the new upstream CLI. Currently it is easy to miss that you need to add `~/.radicle/bin` to the search path to make this happen. To improve on this we should notify the user about this when Upstream starts.

Questions 

* How reliably can we detect that the user has the search path configured properly?
* How do we deal with false positives?
* Do we always use auto detection or do we always show the notification when the user starts Upstream for the first time?

**Comment by rudolfs** [comment] 2022-04-13 14:44
Duplicate of: https://github.com/radicle-dev/radicle-upstream/issues/2802.

**Closed by rudolfs** 2022-04-13 14:44 UTC
Labels: mvp
