### ISSUE TITLE
Make it possible to change display name

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-upstream#2612] opened 2021-11-18 07:10 UTC

**Comment by rudolfs** [comment] 2021-11-18 19:58
Is this a duplicate of https://github.com/radicle-dev/radicle-upstream/issues/635?

**Comment by brandonhaslegs** [comment] 2021-11-18 19:58
Yes, I knew I had an issue already somewhere but couldn't find it!

**Closed** 2021-11-18 19:59 UTC
Labels: feature, design-needed
